modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/ancient-apparition/issues"

[[mods]]
modId = "ancient_apparition"
version = "${file.jarVersion}"
displayName = "Ancient Apparition"
displayURL="https://github.com/JamCoreModding/ancient-apparition"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
TODO
'''

[[dependencies.ancient_apparition]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ancient_apparition]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ancient_apparition]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ancient_apparition]]
modId = "jamlib"
type = "required"
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "ancient_apparition.mixins.json"
